name: Compile Typst Documents
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile Typst Files
      uses: typst-community/setup-typst@v2
      with:
        source_paths: 'main.typ'
        output_paths: 'main.pdf'