name: Compile Typst Documents
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile Typst Files
      uses: typst-community/setup-typst@v2
      with:
        version: latest
        cache: true

    - name: Compile main document
      run: typst compile main.typ main.pdf

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        keep_files: false
        allow_empty_commit: true
        force_orphan: true