name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: NeuralSpeedster/Math_CS_Handbook@main
        with:
          source_file: main.typ